Geoalert/mapflow-qgis

login_dialog.ui
=> Add "Need an account?" & rename password to token

mapflow/config.py, mapflow/dialogs.py, mapflow/helpers.py, mapflow/http.py, mapflow/mapflow.py, mapflow/static/ui/aws_image_id_dialog.ui, mapflow/static/ui/main_dialog.ui, mapflow/static/ui/sentinel_hub_token_dialog.ui
Add support for Sentinel Hub metadata and imagery
=> Sentinel metadata

mapflow/mapflow.py
Disable credentials when selecting sentinel-2 and enable back for anн other provider. Tested locally, all OK
=> disable-enable credential (sentinel-2)

mapflow/mapflow.py
If you add env 'project_id' with a proper ID, you will get (and post) processings from a certain project. Advanced feature for administrators.
=> add project name to footer

mapflow/dialogs/static/ui/main_dialog.ui, mapflow/entity/provider/factory.py, mapflow/mapflow.py
before: were errors when plugin is logged in successfully, but image upload fails with unknown error
after: fixed
=> fix problem with whitemaps/catalog inconsistency

mapflow/requests/__init__.py
Works for me; will need test for installation to the clean QGIS to find out if the problem is solved
=> remove unused/non-existing import

mapflow/config.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/http.py, mapflow/mapflow.py
Added processing rating: UI changes. Needs to be tested
=> Star rating

mapflow/dialogs/static/ui/main_dialog.ui
change processing steps' order in the sidebar in accordance with Mapflow Web scenario
=> UI small edits

mapflow/dialogs/static/ui/main_dialog.ui
=> Edit setting design

mapflow/config.py, mapflow/dialogs/__init__.py, mapflow/dialogs/dialogs.py, mapflow/dialogs/main_dialog.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/dialogs/static/ui/review_dialog.ui, mapflow/entity/billing.py, mapflow/entity/processing.py, mapflow/entity/processing_params.py, mapflow/entity/status.py, mapflow/functional/layer_utils.py, mapflow/mapflow.py
Unacceptable images are shown in source list, but produce visible error when selected
=> Show bad images

mapflow/mapflow.py
Fix some connections for better behavior:
1. Click on outsiide of cells, but in the table, now disables review/rating
2. rating/feedback text is not requested every time by timer
3. removed some non-used connections
=> Display review until

mapflow/config.py, mapflow/constants.py, mapflow/dialogs/main_dialog.py, mapflow/entity/provider/__init__.py, mapflow/entity/provider/default.py, mapflow/http.py, mapflow/mapflow.py, mapflow/schema/__init__.py, mapflow/schema/base.py, mapflow/schema/catalog.py, mapflow/schema/processing.py
Request image search in Mapflow data catalog
display results in table just like for Maxar catalog
not discard UI state on close/open of window
=> Catalog request

mapflow/constants.py, mapflow/dialogs/main_dialog.py, mapflow/functional/layer_utils.py, mapflow/mapflow.py
Similar changes as in preview_osm branch, but without the OSM component
=> Preview without OSM

mapflow/dialogs/static/ui/main_dialog.ui, mapflow/functional/controller/data_catalog_controller.py, mapflow/functional/service/data_catalog.py, mapflow/functional/view/data_catalog_view.py
New version of approved 'image_info' branch without conflicts (the old branch will be deleted)
=> Image Details

mapflow/dialogs/static/ui/main_dialog.ui, mapflow/functional/controller/data_catalog_controller.py, mapflow/functional/service/data_catalog.py, mapflow/functional/view/data_catalog_view.py, mapflow/schema/data_catalog.py
New version of approved 'show_storage' branch without conflicts
=> Storage info

mapflow/dialogs/static/ui/main_dialog.ui, mapflow/functional/api/data_catalog_api.py, mapflow/functional/controller/data_catalog_controller.py, mapflow/functional/service/data_catalog.py, mapflow/functional/view/data_catalog_view.py, mapflow/schema/data_catalog.py
No conflicts duplicate of approved 'image_preview_s' branch + removing preview and info when image is deselected
=> Image preview small

mapflow/dialogs/static/ui/main_dialog.ui, mapflow/functional/api/data_catalog_api.py, mapflow/functional/controller/data_catalog_controller.py, mapflow/functional/layer_utils.py, mapflow/functional/service/data_catalog.py, mapflow/mapflow.py
New version of approved 'image_preview_on_a_map' branch
=> Image preview on a map (large)

mapflow/dialogs/main_dialog.py, mapflow/dialogs/mosaic_dialog.py, mapflow/dialogs/static/ui/mosaic_dialog.ui, mapflow/functional/api/data_catalog_api.py, mapflow/functional/controller/data_catalog_controller.py, mapflow/functional/service/data_catalog.py, mapflow/functional/view/data_catalog_view.py
New version of 'mosaic_add' branch (#116) without conflicts
=> Mosaic CRUD

CHANGELOG.md, mapflow/dialogs/main_dialog.py, mapflow/mapflow.py, mapflow/metadata.txt
Specify imagery search preview footprint by GCPs from polygon corners
=> Preview shift fix

mapflow/functional/layer_utils.py, mapflow/http.py, mapflow/mapflow.py
- Makes processing start unavailable when geometry count is greater than 10 (includong multipart)
- Gives a clear message if processing was somehow still started with too many AOIs
=> Multipolygon AOI count

mapflow/config.py, mapflow/dialogs/main_dialog.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/entity/provider/basemap_provider.py, mapflow/entity/provider/default.py, mapflow/entity/provider/provider.py, mapflow/mapflow.py, mapflow/schema/processing.py
Add zoom spinbox when variable is True and add 'zoom' to processing params
=> Zoom spinBox

mapflow/functional/service/data_catalog.py, mapflow/functional/view/data_catalog_view.py
Processing area does not update when using get_mosaic_images, use get_mosaic instead
=> Fix area get mosaic

mapflow/config.py, mapflow/dialogs/main_dialog.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/functional/service/data_catalog.py, mapflow/mapflow.py, mapflow/schema/catalog.py
- Hide unavailable providers
- Choose product types
- Configure search table in settings
=> Search: hide anavailable, choose product type, show additional columns

mapflow/functional/service/data_catalog.py
Show clear error when uploading, but mosaic isn't selected + Request images after upload
=> Error when uploading (mosaic is None) + get_mosaic_images

mapflow/entity/provider/provider.py, mapflow/functional/helpers.py, mapflow/mapflow.py
- Timeout
- Pathlib
- Disable zoom for My imagery
=> Small fixes 3.1

mapflow/static/styles/file/forest_with_heights.qml, mapflow/styles.py
Display style for the updated default model
=> display 'Forest and trees' style

mapflow/dialogs/static/ui/main_dialog.ui, mapflow/functional/layer_utils.py, mapflow/mapflow.py
- Remove adding AOI from file (not adding to layers)
- Substitude 'use imagery extent' checkbox with an option inside "+" and rename it according to selection
=> AOI options menu

mapflow/config.py, mapflow/dialogs/main_dialog.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/mapflow.py
Because here we have multiple columns (and plus they can be hidden), we can not implement completely the same solution as for My imagery.
Here is my workaround with the separate Preview column. What do you think?
=> Search: Add column with preview label

mapflow/dialogs/dialogs.py, mapflow/dialogs/main_dialog.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/dialogs/static/ui/processing_start_confirmation.ui, mapflow/mapflow.py
- Show a window with all chosen processing parameters to confirm and a checkbox to not show this again
- In settings, add checkbox to be able to turn confirmation back on
=> Processings: Confirm parameters before start

mapflow/dialogs/main_dialog.py, mapflow/dialogs/static/ui/main_dialog.ui, mapflow/mapflow.py, mapflow/schema/catalog.py
If nothing changed in additional filters - send None, else - checked providers names
=> Search: Add combo for providers filter

mapflow/mapflow.py, mapflow/schema/catalog.py
- Add JPG type
- Handle no previewType ("Selected imagery has no preview")
- Handle no PreviewUrl ("Preview with such URL is unavailable")
=> Search: Add JPG preview support and handle empty preview and url fields
